name: Cue
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  provider: ^5.0.0
  google_fonts: ^2.1.0
  video_player: ^2.1.12
  # video_player_controls: ^2.1.9
  flutter_spinkit: ^5.0.0
  # it was good,,
  # configurable_expansion_tile: ^1.0.0
  camera: ^0.8.1+7
  stop_watch_timer: ^1.3.1
  fluttertoast: ^8.0.7
  # screen: ^0.0.5
  permission_handler: ^8.1.4+2 #dubbing recoder request
  # audioplayers: ^0.17.4
  # flutter_sound: ^7.5.3+1 #dubbing.dart
  animations: ^2.0.1
  # neeko: ^0.0.10
  flutter_search_bar: ^3.0.0-dev.1
  # neeko:
  #   git:
  #     url: https://github.com/Cue-dev/neeko.git
  #     ref: master
      
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/cueLogo1.png
    - images/cueLogo.png
    - icons/홈.png
    - icons/검색.png
    - icons/인기.png
    - icons/마이.png
    - icons/메뉴.png
    - icons/큐.png
    - icons/큐_활성.png
    - icons/피드.png
    - icons/알림.png
    - icons/알림_유.png
    - icons/하트.png
    - icons/하트_선택.png
    - icons/대본저장.png
    - icons/영상대본저장.png
    - icons/섀도잉.png
    - icons/공유.png
    - icons/취소.png
    - icons/라이브러리.png
    # 임시
    - images/1.png
    - images/2.png
    - images/3.png
    - icons/녹음.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansCJK
      fonts:
        - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Light.otf
        - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Medium.otf
        - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Regular.otf
    - family: HelveticaMedium
      fonts:
        - asset: assets/fonts/HelveticaMedium/helvmn.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
